# Generated by Django 4.0.6 on 2022-07-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='control_de_descartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ant_caja_n', models.IntegerField()),
                ('t_ant_cantidad_n', models.IntegerField()),
                ('t_act_caja_n', models.IntegerField()),
                ('t_act_cantidad_n', models.IntegerField()),
                ('piezas_por_caja', models.IntegerField()),
                ('tipo_lente', models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('neon', 'Neon')], default='argon', max_length=12, verbose_name='Tipo de lente')),
            ],
        ),
        migrations.CreateModel(
            name='fin_de_op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tiempo_de_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('hc', 'Hc'), ('af', 'Af')], default='Hc', max_length=2, verbose_name='Tipo de proceso')),
                ('tipo_lente', models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('fall dual', 'Fall dual'), ('argon elite', 'Argon Elite'), ('neon', 'Neon'), ('new classic', 'New classic'), ('aviator', 'Aviator')], default='argon', max_length=12, verbose_name='Tipo de lente')),
                ('tiempo_ciclo', models.IntegerField(verbose_name='Tiempo de ciclo')),
                ('tiempo_carro', models.IntegerField(default=None)),
                ('fecha_creacion', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'tiempo_de_carro',
            },
        ),
    ]
