# Generated by Django 4.0.4 on 2022-07-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lentes',
            name='Valor3',
        ),
        migrations.RemoveField(
            model_name='lentes',
            name='Valor4',
        ),
    ]
