# Generated by Django 4.0.6 on 2022-07-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo_de_carro',
            name='fecha_creacion',
        ),
    ]
