# Generated by Django 4.0.4 on 2022-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0002_remove_lentes_valor3_remove_lentes_valor4'),
    ]

    operations = [
        migrations.AddField(
            model_name='lentes',
            name='Valor4',
            field=models.IntegerField(null=True),
        ),
    ]
