# Generated by Django 4.0.4 on 2022-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0003_alter_tiempo_de_carro_tiempo_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_de_descartes',
            name='piezas_buenas',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='control_de_descartes',
            name='piezas_descartadas',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='control_de_descartes',
            name='piezas_malas',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='control_de_descartes',
            name='peso_en_kg',
            field=models.IntegerField(default=None),
        ),
    ]
