# Generated by Django 4.0.4 on 2022-07-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0003_lentes_valor4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lentes',
            name='Valor4',
        ),
    ]
