# Generated by Django 4.0.4 on 2022-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0004_remove_lentes_valor4'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiempo_de_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(max_length=30)),
                ('tipo_lente', models.CharField(max_length=200)),
                ('cantidad_rotulos', models.IntegerField()),
                ('piezas_caja', models.IntegerField()),
            ],
            options={
                'db_table': 'tiempo_de_carro',
            },
        ),
        migrations.DeleteModel(
            name='Lentes',
        ),
    ]
