# Generated by Django 4.0.4 on 2022-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0005_tiempo_de_carro_delete_lentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiempo_de_carro',
            old_name='cantidad_rotulos',
            new_name='tiempo_ciclo',
        ),
        migrations.RemoveField(
            model_name='tiempo_de_carro',
            name='piezas_caja',
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.IntegerField(choices=[(1, 'Argon'), (2, 'Ecoline'), (3, 'Mig'), (4, 'Fall dual'), (5, 'Argon Elite'), (6, 'Neon'), (7, 'New classic')]),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.IntegerField(choices=[(1, 'Hc'), (2, 'Af')]),
        ),
    ]
