# Generated by Django 4.0.4 on 2022-07-22 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0006_tiempo_de_carro_fecha_y_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='fecha_y_hora',
            field=models.TimeField(default=datetime.datetime(2022, 7, 22, 12, 8, 53, 964600)),
        ),
    ]
