# Generated by Django 4.0.4 on 2022-07-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0006_rename_cantidad_rotulos_tiempo_de_carro_tiempo_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.IntegerField(choices=[(1, 'Argon'), (2, 'Ecoline'), (3, 'Mig'), (4, 'Fall dual'), (5, 'Argon Elite'), (6, 'Neon'), (7, 'New classic')], default=1),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.IntegerField(choices=[(1, 'Hc'), (2, 'Af')], default=1),
        ),
    ]
