# Generated by Django 4.0.4 on 2022-07-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0007_alter_tiempo_de_carro_tipo_lente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.IntegerField(choices=[('Hc', 1), ('Af', 2)], default=1),
        ),
    ]
