# Generated by Django 4.0.6 on 2022-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0009_alter_tiempo_de_carro_tiempo_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tiempo_ciclo',
            field=models.IntegerField(null=True, verbose_name='Tiempo de ciclo'),
        ),
    ]
