# Generated by Django 4.0.6 on 2022-07-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0010_alter_tiempo_de_carro_tiempo_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.CharField(choices=[(1, 'Hc'), (2, 'Af')], default='Hc', max_length=2, verbose_name='Tipo de proceso'),
        ),
    ]
