# Generated by Django 4.0.4 on 2022-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0011_alter_tiempo_de_carro_tipo_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.CharField(choices=[('hc', 'Hc'), ('af', 'Af')], default='Hc', max_length=2),
        ),
    ]
