# Generated by Django 4.0.6 on 2022-07-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0012_alter_tiempo_de_carro_tipo_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo_de_carro',
            name='tiempo_carro',
        ),
    ]
