# Generated by Django 4.0.4 on 2022-07-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0012_alter_tiempo_de_carro_fecha_y_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo_de_carro',
            name='fecha_y_hora',
        ),
    ]
