# Generated by Django 4.0.4 on 2022-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0013_alter_tiempo_de_carro_tipo_lente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.CharField(max_length=2),
        ),
    ]
