# Generated by Django 4.0.4 on 2022-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0013_remove_tiempo_de_carro_fecha_y_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_de_descartes',
            name='piezas_buenas',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='control_de_descartes',
            name='piezas_descartadas',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='control_de_descartes',
            name='piezas_malas',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
