# Generated by Django 4.0.4 on 2022-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0014_alter_tiempo_de_carro_tipo_lente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tiempo_ciclo',
            field=models.IntegerField(verbose_name='Tiempo de ciclo'),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('fall dual', 'Fall dual'), ('argon elite', 'Argon Elite'), ('neon', 'Neon'), ('neon classic', 'New classic')], default='argon', max_length=12, verbose_name='Tipo de lente'),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_proceso',
            field=models.CharField(choices=[('hc', 'Hc'), ('af', 'Af')], default='Hc', max_length=2, verbose_name='Tipo de proceso'),
        ),
    ]
