# Generated by Django 4.0.4 on 2022-07-22 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0014_alter_control_de_descartes_piezas_buenas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempo_de_carro',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 14, 58, 30, 809743, tzinfo=utc)),
        ),
    ]
