# Generated by Django 4.0.4 on 2022-07-22 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0015_tiempo_de_carro_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 14, 58, 44, 816884, tzinfo=utc)),
        ),
    ]
