# Generated by Django 4.0.4 on 2022-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0015_alter_tiempo_de_carro_tiempo_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('fall dual', 'Fall dual'), ('argon elite', 'Argon Elite'), ('neon', 'Neon'), ('new classic', 'New classic')], default='argon', max_length=12, verbose_name='Tipo de lente'),
        ),
    ]
