# Generated by Django 4.0.4 on 2022-07-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0016_alter_tiempo_de_carro_tipo_lente'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_de_descartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ant_caja_n', models.IntegerField()),
                ('t_ant_cantidad_n', models.IntegerField()),
                ('t_act_caja_n', models.IntegerField()),
                ('t_act_cantidad_n', models.IntegerField()),
                ('piezas_por_caja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='fin_de_op',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
