# Generated by Django 4.0.4 on 2022-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0017_control_de_descartes_fin_de_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_de_descartes',
            name='tipo_lente',
            field=models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('fall dual', 'Fall dual'), ('argon elite', 'Argon Elite'), ('neon', 'Neon'), ('new classic', 'New classic'), ('aviator', 'Aviator')], default='argon', max_length=12, verbose_name='Tipo de lente'),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='tipo_lente',
            field=models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('fall dual', 'Fall dual'), ('argon elite', 'Argon Elite'), ('neon', 'Neon'), ('new classic', 'New classic'), ('aviator', 'Aviator')], default='argon', max_length=12, verbose_name='Tipo de lente'),
        ),
    ]
