# Generated by Django 4.0.4 on 2022-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0018_control_de_descartes_tipo_lente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_de_descartes',
            name='tipo_lente',
            field=models.CharField(choices=[('argon', 'Argon'), ('ecoline', 'Ecoline'), ('mig', 'Mig'), ('neon', 'Neon')], default='argon', max_length=12, verbose_name='Tipo de lente'),
        ),
    ]
