# Generated by Django 4.0.4 on 2022-07-22 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lentes', '0020_tiempo_de_carro_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_de_descartes',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 17, 48, 40, 744653, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='control_de_descartes',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='mañana', max_length=10),
        ),
        migrations.AddField(
            model_name='fin_de_op',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 17, 48, 40, 744891, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='fin_de_op',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='mañana', max_length=10),
        ),
        migrations.AlterField(
            model_name='tiempo_de_carro',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 17, 48, 40, 744324, tzinfo=utc)),
        ),
    ]
